### ISSUE TITLE
消息通知暂时不可用了, 看起来是知乎APInoti4接口下线了.

### ISSUE THREAD

**Issue by liguobao** [Damao/zhihu#1]
新接口
https://www.zhihu.com/api/v4/notifications/v2/vote_thank?limit=10&offset=1561302790

**Comment by Damao** [comment]
呃…………现在从天天加班的码农转职成了天天加班的设计师……
JSON结构一致嘛？大佬要么帮忙提个PR？ 我不知道啥时候能抽身出来……

**Comment by Damao** [comment]
发布了，等审核~

**Comment by liguobao** [comment]
有点惨, 天天加班ing..
好好一个dalao咋就去做设计了...
